### ISSUE TITLE
Many-to-Many relationship (using through) errors

### ISSUE THREAD

**Issue by AskYous** [AskYous/sails-my-admin#10]
When a many-to-many relationship is used, and the `through` is used for that, an error occurs which is that 1 of the models does not submit to the database when editing a model.

(I plan to expand on this later).

**Comment by AskYous** [comment]
Current waiting on SailsJS to repond to my issue:

https://github.com/balderdashy/sails/issues/3946

**Comment by AskYous** [comment]
I had a similar error at work. I had a parent subject which had child courses. Updating the subject throws a server error saying that the child course(s) were missing parent subjects. I fixed it by making the course's subject not required. Everything worked and the links aren't broken when updating the parent subject.

**Comment by AskYous** [comment]
Sails said it's been fixed, but I tried again and it still errors.

**Comment by itssoso** [comment]
I tried this and it seems to be working.  Maybe you need to explain this to me.

**Comment by AskYous** [comment]
@soullessknight I re-created the sails issue [here](https://github.com/AskYous/sails-through-error). Does it work for you there too?
